### ISSUE TITLE
Pool struct fails to parse on newly created but empty pools

### ISSUE THREAD

**Issue by ArcticSnowman** [shiftky/go-tmsh#17] opened 2018-03-19 15:11 UTC
When a pool in BigIP is newly created, the TMSH call to get the pool definition does not return a status.status-reason.  

There needs to be the ability to do the equivalent of the JSON 'omitempty' empty

```
// Pool contains information about each Pool
type Pool struct {
	ActiveMemberCount int          `ltm:"active-member-cnt"`
	Name              string       `ltm:"name"`
	MonitorRule       string       `ltm:"monitor-rule"`
	AvailabilityState string       `ltm:"status.availability-state"`
	EnabledState      string       `ltm:"status.enabled-state"`
	StatusReason      string       `ltm:"status.status-reason"`
	PoolMembers       []PoolMember `ltm:"members"`
}

```

**Comment by shiftky** [comment] 2018-03-21 09:36
@ArcticSnowman You can get the fix that was just pushed. (please checkout branch: `git checkout issue17-fix_parser_bug`) 
Can you confirm that the problem is being resolved?

**Comment by ArcticSnowman** [comment] 2018-03-21 13:12
We will pull the branch into our fork..  We have a SSH via Key enhancement that we will be submitted to you shortly and need to merge these for the code.

**Comment by shiftky** [comment] 2018-04-01 05:19
@ArcticSnowman How are things going? If you can confirm that it's has been solved, I will merge #18  and close this issue.

**Comment by ArcticSnowman** [comment] 2018-04-02 13:30
It's working fine for us...

**Comment by shiftky** [comment] 2018-04-03 02:36
Thanks for your confirmation!

**Closed** 2018-04-03 02:36 UTC
Labels: bug
